In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 변수 처리

In [2]:
df = pd.read_csv('league_5_div_HTR_Date_Oa_MV_X.csv')

df.head()

Date         HomeTeam     AwayTeam  HomeSquad  AwaySquad  HomeAvgAge  \
0  2014-09-26            Elche   Celta Vigo       29.0       28.0        25.0   
1  2014-09-27  Atletico Madrid      Sevilla       32.0       34.0        25.0   
2  2014-09-27       Villarreal  Real Madrid       37.0       41.0        24.0   
3  2014-09-27    Athletic Club        Eibar       27.0       25.0        26.0   
4  2014-09-27        Barcelona      Granada       31.0       39.0        25.0   

   AwayAvgAge  FTHG  FTAG FTR  ...   HR   AR    HxG    AxG    HxA    AxA  \
0        24.0   1.0   2.0   A  ...  0.0  0.0  0.828  1.536  0.456  0.974   
1        25.0   1.4   1.8   H  ...  0.0  0.0  1.500  1.846  1.376  1.082   
2        24.0   1.4   3.6   A  ...  0.0  0.0  1.958  2.104  1.472  1.502   
3        28.0   0.8   1.0   D  ...  0.0  0.0  1.002  0.686  0.788  0.552   
4        25.0   2.2   0.8   H  ...  0.2  0.0  2.264  0.552  1.444  0.330   

   HxPTS  AxPTS   HPPDA  APPDA  
0  0.844  1.696  12.440  6.458  
1  1.910  2.104  11.820  8.262  
2  1.710  1.760  13.016  8.634  
3  1.080  1.074   7.822  9.050  
4  2.544  1.222   6.064  8.726  

[5 rows x 32 columns]

In [3]:
df = df.replace({'FTR' : 'H'}, 0)
df = df.replace({'FTR' : 'A'}, 1)
df = df.replace({'FTR' : 'D'}, 2)

In [4]:
df = df.dropna()

In [5]:
df = df.drop(['HTOa', 'ATOa', 'FTHG', 'FTAG'], axis=1)
df

KeyError: "['HTOa', 'ATOa'] not found in axis"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12548 entries, 0 to 12547
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Date        12548 non-null  object 
 1   HomeTeam    12548 non-null  object 
 2   AwayTeam    12548 non-null  object 
 3   HomeSquad   12548 non-null  float64
 4   AwaySquad   12548 non-null  float64
 5   HomeAvgAge  12548 non-null  float64
 6   AwayAvgAge  12548 non-null  float64
 7   FTHG        12548 non-null  float64
 8   FTAG        12548 non-null  float64
 9   FTR         12548 non-null  int64  
 10  HTHG        12548 non-null  float64
 11  HTAG        12548 non-null  float64
 12  HS          12548 non-null  float64
 13  AS          12548 non-null  float64
 14  HST         12548 non-null  float64
 15  AST         12548 non-null  float64
 16  HF          12548 non-null  float64
 17  AF          12548 non-null  float64
 18  HC          12548 non-null  float64
 19  AC          12548 non-nul

In [ ]:
df[df.isna( ).any(axis=1)]

Empty DataFrame
Columns: [Date, HomeTeam, AwayTeam, HomeSquad, AwaySquad, HomeAvgAge, AwayAvgAge, FTHG, FTAG, FTR, HTHG, HTAG, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR, HxG, AxG, HxA, AxA, HxPTS, AxPTS, HPPDA, APPDA]
Index: []

[0 rows x 32 columns]

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df['month'] = df['Date'].dt.month

In [ ]:
df

Date             HomeTeam           AwayTeam  HomeSquad  \
0     2014-09-26                Elche         Celta Vigo       29.0   
1     2014-09-27      Atletico Madrid            Sevilla       32.0   
2     2014-09-27           Villarreal        Real Madrid       37.0   
3     2014-09-27        Athletic Club              Eibar       27.0   
4     2014-09-27            Barcelona            Granada       31.0   
...          ...                  ...                ...        ...   
12543 2021-09-25         Union Berlin  Arminia Bielefeld       40.0   
12544 2021-09-25     Bayer Leverkusen           Mainz 05       35.0   
12545 2021-09-25           Hoffenheim          Wolfsburg       40.0   
12546 2021-09-25  Eintracht Frankfurt         FC Cologne       36.0   
12547 2021-09-24      Greuther Fuerth      Bayern Munich       34.0   

       AwaySquad  HomeAvgAge  AwayAvgAge  FTHG  FTAG  FTR  ...   AR    HxG  \
0           28.0        25.0        24.0   1.0   2.0    1  ...  0.0  0.828   
1           34.0        25.0        25.0   1.4   1.8    0  ...  0.0  1.500   
2           41.0        24.0        24.0   1.4   3.6    1  ...  0.0  1.958   
3           25.0        26.0        28.0   0.8   1.0    2  ...  0.0  1.002   
4           39.0        25.0        25.0   2.2   0.8    0  ...  0.0  2.264   
...          ...         ...         ...   ...   ...  ...  ...  ...    ...   
12543       34.0        26.0        24.0   1.4   0.6    0  ...  0.2  1.560   
12544       34.0        24.0        24.0   3.0   1.2    0  ...  0.0  1.384   
12545       37.0        24.0        25.0   1.6   1.4    0  ...  0.0  1.776   
12546       31.0        25.0        25.0   1.0   1.8    2  ...  0.2  1.248   
12547       38.0        24.0        24.0   0.6   4.0    1  ...  0.0  1.226   

         AxG    HxA    AxA  HxPTS  AxPTS   HPPDA   APPDA  month  
0      1.536  0.456  0.974  0.844  1.696  12.440   6.458      9  
1      1.846  1.376  1.082  1.910  2.104  11.820   8.262      9  
2      2.104  1.472  1.502  1.710  1.760  13.016   8.634      9  
3      0.686  0.788  0.552  1.080  1.074   7.822   9.050      9  
4      0.552  1.444  0.330  2.544  1.222   6.064   8.726      9  
...      ...    ...    ...    ...    ...     ...     ...    ...  
12543  0.902  1.118  0.634  1.762  0.642  16.288  13.936      9  
12544  1.414  1.140  0.830  1.316  1.930  12.608  11.290      9  
12545  1.550  1.512  0.816  1.366  1.914  11.720   8.246      9  
12546  1.738  1.018  1.398  1.384  1.376   7.686   7.152      9  
12547  4.288  0.590  3.230  0.926  2.720  12.116   9.254      9  

[12548 rows x 33 columns]

In [ ]:
df = df.drop(['Date'], axis = 1)

In [ ]:
df

HomeTeam           AwayTeam  HomeSquad  AwaySquad  \
0                    Elche         Celta Vigo       29.0       28.0   
1          Atletico Madrid            Sevilla       32.0       34.0   
2               Villarreal        Real Madrid       37.0       41.0   
3            Athletic Club              Eibar       27.0       25.0   
4                Barcelona            Granada       31.0       39.0   
...                    ...                ...        ...        ...   
12543         Union Berlin  Arminia Bielefeld       40.0       34.0   
12544     Bayer Leverkusen           Mainz 05       35.0       34.0   
12545           Hoffenheim          Wolfsburg       40.0       37.0   
12546  Eintracht Frankfurt         FC Cologne       36.0       31.0   
12547      Greuther Fuerth      Bayern Munich       34.0       38.0   

       HomeAvgAge  AwayAvgAge  FTHG  FTAG  FTR  HTHG  ...   AR    HxG    AxG  \
0            25.0        24.0   1.0   2.0    1   0.4  ...  0.0  0.828  1.536   
1            25.0        25.0   1.4   1.8    0   1.0  ...  0.0  1.500  1.846   
2            24.0        24.0   1.4   3.6    1   0.2  ...  0.0  1.958  2.104   
3            26.0        28.0   0.8   1.0    2   0.4  ...  0.0  1.002  0.686   
4            25.0        25.0   2.2   0.8    0   0.6  ...  0.0  2.264  0.552   
...           ...         ...   ...   ...  ...   ...  ...  ...    ...    ...   
12543        26.0        24.0   1.4   0.6    0   0.8  ...  0.2  1.560  0.902   
12544        24.0        24.0   3.0   1.2    0   1.8  ...  0.0  1.384  1.414   
12545        24.0        25.0   1.6   1.4    0   0.6  ...  0.0  1.776  1.550   
12546        25.0        25.0   1.0   1.8    2   0.6  ...  0.2  1.248  1.738   
12547        24.0        24.0   0.6   4.0    1   0.0  ...  0.0  1.226  4.288   

         HxA    AxA  HxPTS  AxPTS   HPPDA   APPDA  month  
0      0.456  0.974  0.844  1.696  12.440   6.458      9  
1      1.376  1.082  1.910  2.104  11.820   8.262      9  
2      1.472  1.502  1.710  1.760  13.016   8.634      9  
3      0.788  0.552  1.080  1.074   7.822   9.050      9  
4      1.444  0.330  2.544  1.222   6.064   8.726      9  
...      ...    ...    ...    ...     ...     ...    ...  
12543  1.118  0.634  1.762  0.642  16.288  13.936      9  
12544  1.140  0.830  1.316  1.930  12.608  11.290      9  
12545  1.512  0.816  1.366  1.914  11.720   8.246      9  
12546  1.018  1.398  1.384  1.376   7.686   7.152      9  
12547  0.590  3.230  0.926  2.720  12.116   9.254      9  

[12548 rows x 32 columns]

In [ ]:
# df.loc[df['HR'] >= 1, 'HR'] = 1 # 레드카드의 유무로 변경 (있으면 1 / 없으면 0)
# df.loc[df['HR'] < 1, 'HR'] = 0

# df

In [ ]:
# df.loc[df['AR'] >= 1, 'AR'] = 1
# df.loc[df['AR'] < 1, 'AR'] = 0

# df

In [ ]:
# print(df['HR'].unique())
# print(df['AR'].unique())

In [ ]:
# Define the bins and labels for categorization
bins = [0, 1, 2, 3]
labels = ['0-1', '1-2', '2-3']

# Categorize HxPTS and AxPTS
df['HxPTS_category'] = pd.cut(df['HxPTS'], bins=bins, labels=labels, include_lowest=True)
df['AxPTS_category'] = pd.cut(df['AxPTS'], bins=bins, labels=labels, include_lowest=True)


df

HomeTeam           AwayTeam  HomeSquad  AwaySquad  \
0                    Elche         Celta Vigo       29.0       28.0   
1          Atletico Madrid            Sevilla       32.0       34.0   
2               Villarreal        Real Madrid       37.0       41.0   
3            Athletic Club              Eibar       27.0       25.0   
4                Barcelona            Granada       31.0       39.0   
...                    ...                ...        ...        ...   
12543         Union Berlin  Arminia Bielefeld       40.0       34.0   
12544     Bayer Leverkusen           Mainz 05       35.0       34.0   
12545           Hoffenheim          Wolfsburg       40.0       37.0   
12546  Eintracht Frankfurt         FC Cologne       36.0       31.0   
12547      Greuther Fuerth      Bayern Munich       34.0       38.0   

       HomeAvgAge  AwayAvgAge  FTHG  FTAG  FTR  HTHG  ...    AxG    HxA  \
0            25.0        24.0   1.0   2.0    1   0.4  ...  1.536  0.456   
1            25.0        25.0   1.4   1.8    0   1.0  ...  1.846  1.376   
2            24.0        24.0   1.4   3.6    1   0.2  ...  2.104  1.472   
3            26.0        28.0   0.8   1.0    2   0.4  ...  0.686  0.788   
4            25.0        25.0   2.2   0.8    0   0.6  ...  0.552  1.444   
...           ...         ...   ...   ...  ...   ...  ...    ...    ...   
12543        26.0        24.0   1.4   0.6    0   0.8  ...  0.902  1.118   
12544        24.0        24.0   3.0   1.2    0   1.8  ...  1.414  1.140   
12545        24.0        25.0   1.6   1.4    0   0.6  ...  1.550  1.512   
12546        25.0        25.0   1.0   1.8    2   0.6  ...  1.738  1.018   
12547        24.0        24.0   0.6   4.0    1   0.0  ...  4.288  0.590   

         AxA  HxPTS  AxPTS   HPPDA   APPDA  month  HxPTS_category  \
0      0.974  0.844  1.696  12.440   6.458      9             0-1   
1      1.082  1.910  2.104  11.820   8.262      9             1-2   
2      1.502  1.710  1.760  13.016   8.634      9             1-2   
3      0.552  1.080  1.074   7.822   9.050      9             1-2   
4      0.330  2.544  1.222   6.064   8.726      9             2-3   
...      ...    ...    ...     ...     ...    ...             ...   
12543  0.634  1.762  0.642  16.288  13.936      9             1-2   
12544  0.830  1.316  1.930  12.608  11.290      9             1-2   
12545  0.816  1.366  1.914  11.720   8.246      9             1-2   
12546  1.398  1.384  1.376   7.686   7.152      9             1-2   
12547  3.230  0.926  2.720  12.116   9.254      9             0-1   

       AxPTS_category  
0                 1-2  
1                 2-3  
2                 1-2  
3                 1-2  
4                 1-2  
...               ...  
12543             0-1  
12544             1-2  
12545             1-2  
12546             1-2  
12547             2-3  

[12548 rows x 34 columns]

In [ ]:
df = df.drop(['HxPTS', 'AxPTS'], axis=1)

df

HomeTeam           AwayTeam  HomeSquad  AwaySquad  \
0                    Elche         Celta Vigo       29.0       28.0   
1          Atletico Madrid            Sevilla       32.0       34.0   
2               Villarreal        Real Madrid       37.0       41.0   
3            Athletic Club              Eibar       27.0       25.0   
4                Barcelona            Granada       31.0       39.0   
...                    ...                ...        ...        ...   
12543         Union Berlin  Arminia Bielefeld       40.0       34.0   
12544     Bayer Leverkusen           Mainz 05       35.0       34.0   
12545           Hoffenheim          Wolfsburg       40.0       37.0   
12546  Eintracht Frankfurt         FC Cologne       36.0       31.0   
12547      Greuther Fuerth      Bayern Munich       34.0       38.0   

       HomeAvgAge  AwayAvgAge  FTHG  FTAG  FTR  HTHG  ...   AR    HxG    AxG  \
0            25.0        24.0   1.0   2.0    1   0.4  ...  0.0  0.828  1.536   
1            25.0        25.0   1.4   1.8    0   1.0  ...  0.0  1.500  1.846   
2            24.0        24.0   1.4   3.6    1   0.2  ...  0.0  1.958  2.104   
3            26.0        28.0   0.8   1.0    2   0.4  ...  0.0  1.002  0.686   
4            25.0        25.0   2.2   0.8    0   0.6  ...  0.0  2.264  0.552   
...           ...         ...   ...   ...  ...   ...  ...  ...    ...    ...   
12543        26.0        24.0   1.4   0.6    0   0.8  ...  0.2  1.560  0.902   
12544        24.0        24.0   3.0   1.2    0   1.8  ...  0.0  1.384  1.414   
12545        24.0        25.0   1.6   1.4    0   0.6  ...  0.0  1.776  1.550   
12546        25.0        25.0   1.0   1.8    2   0.6  ...  0.2  1.248  1.738   
12547        24.0        24.0   0.6   4.0    1   0.0  ...  0.0  1.226  4.288   

         HxA    AxA   HPPDA   APPDA  month  HxPTS_category  AxPTS_category  
0      0.456  0.974  12.440   6.458      9             0-1             1-2  
1      1.376  1.082  11.820   8.262      9             1-2             2-3  
2      1.472  1.502  13.016   8.634      9             1-2             1-2  
3      0.788  0.552   7.822   9.050      9             1-2             1-2  
4      1.444  0.330   6.064   8.726      9             2-3             1-2  
...      ...    ...     ...     ...    ...             ...             ...  
12543  1.118  0.634  16.288  13.936      9             1-2             0-1  
12544  1.140  0.830  12.608  11.290      9             1-2             1-2  
12545  1.512  0.816  11.720   8.246      9             1-2             1-2  
12546  1.018  1.398   7.686   7.152      9             1-2             1-2  
12547  0.590  3.230  12.116   9.254      9             0-1             2-3  

[12548 rows x 32 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12548 entries, 0 to 12547
Data columns (total 32 columns):
 #   Column          Non-Null Count  Dtype   
---  ------          --------------  -----   
 0   HomeTeam        12548 non-null  object  
 1   AwayTeam        12548 non-null  object  
 2   HomeSquad       12548 non-null  float64 
 3   AwaySquad       12548 non-null  float64 
 4   HomeAvgAge      12548 non-null  float64 
 5   AwayAvgAge      12548 non-null  float64 
 6   FTHG            12548 non-null  float64 
 7   FTAG            12548 non-null  float64 
 8   FTR             12548 non-null  int64   
 9   HTHG            12548 non-null  float64 
 10  HTAG            12548 non-null  float64 
 11  HS              12548 non-null  float64 
 12  AS              12548 non-null  float64 
 13  HST             12548 non-null  float64 
 14  AST             12548 non-null  float64 
 15  HF              12548 non-null  float64 
 16  AF              12548 non-null  float64 
 17  HC          

In [ ]:
label = df['HxPTS_category']
label.unique()

['0-1', '1-2', '2-3']
Categories (3, object): ['0-1' < '1-2' < '2-3']

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)

In [ ]:
label.values
label.values.reshape(-1, 1)
ohe.fit(label.values.reshape(-1,1))

OneHotEncoder(sparse=False)

In [ ]:
ohe.transform(label.values.reshape(-1,1))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
label_test = np.array([['0-1'], ['1-2'], ['2-3']])

In [ ]:
ohe.transform(label_test)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ohe.categories_

[array(['0-1', '1-2', '2-3'], dtype=object)]

In [ ]:
label_ohe = ohe.transform(label.values.reshape(-1, 1))

ohe_df = pd.DataFrame(label_ohe, columns=['H0-1', 'H1-2', 'H2-3'])
ohe_df

H0-1  H1-2  H2-3
0       1.0   0.0   0.0
1       0.0   1.0   0.0
2       0.0   1.0   0.0
3       0.0   1.0   0.0
4       0.0   0.0   1.0
...     ...   ...   ...
12543   0.0   1.0   0.0
12544   0.0   1.0   0.0
12545   0.0   1.0   0.0
12546   0.0   1.0   0.0
12547   1.0   0.0   0.0

[12548 rows x 3 columns]

In [ ]:
df = pd.concat([df, ohe_df], axis=1).drop('HxPTS_category', axis=1)

In [ ]:
df

HomeTeam           AwayTeam  HomeSquad  AwaySquad  \
0                    Elche         Celta Vigo       29.0       28.0   
1          Atletico Madrid            Sevilla       32.0       34.0   
2               Villarreal        Real Madrid       37.0       41.0   
3            Athletic Club              Eibar       27.0       25.0   
4                Barcelona            Granada       31.0       39.0   
...                    ...                ...        ...        ...   
12543         Union Berlin  Arminia Bielefeld       40.0       34.0   
12544     Bayer Leverkusen           Mainz 05       35.0       34.0   
12545           Hoffenheim          Wolfsburg       40.0       37.0   
12546  Eintracht Frankfurt         FC Cologne       36.0       31.0   
12547      Greuther Fuerth      Bayern Munich       34.0       38.0   

       HomeAvgAge  AwayAvgAge  FTHG  FTAG  FTR  HTHG  ...    AxG    HxA  \
0            25.0        24.0   1.0   2.0    1   0.4  ...  1.536  0.456   
1            25.0        25.0   1.4   1.8    0   1.0  ...  1.846  1.376   
2            24.0        24.0   1.4   3.6    1   0.2  ...  2.104  1.472   
3            26.0        28.0   0.8   1.0    2   0.4  ...  0.686  0.788   
4            25.0        25.0   2.2   0.8    0   0.6  ...  0.552  1.444   
...           ...         ...   ...   ...  ...   ...  ...    ...    ...   
12543        26.0        24.0   1.4   0.6    0   0.8  ...  0.902  1.118   
12544        24.0        24.0   3.0   1.2    0   1.8  ...  1.414  1.140   
12545        24.0        25.0   1.6   1.4    0   0.6  ...  1.550  1.512   
12546        25.0        25.0   1.0   1.8    2   0.6  ...  1.738  1.018   
12547        24.0        24.0   0.6   4.0    1   0.0  ...  4.288  0.590   

         AxA   HPPDA   APPDA  month  AxPTS_category  H0-1  H1-2  H2-3  
0      0.974  12.440   6.458      9             1-2   1.0   0.0   0.0  
1      1.082  11.820   8.262      9             2-3   0.0   1.0   0.0  
2      1.502  13.016   8.634      9             1-2   0.0   1.0   0.0  
3      0.552   7.822   9.050      9             1-2   0.0   1.0   0.0  
4      0.330   6.064   8.726      9             1-2   0.0   0.0   1.0  
...      ...     ...     ...    ...             ...   ...   ...   ...  
12543  0.634  16.288  13.936      9             0-1   0.0   1.0   0.0  
12544  0.830  12.608  11.290      9             1-2   0.0   1.0   0.0  
12545  0.816  11.720   8.246      9             1-2   0.0   1.0   0.0  
12546  1.398   7.686   7.152      9             1-2   0.0   1.0   0.0  
12547  3.230  12.116   9.254      9             2-3   1.0   0.0   0.0  

[12548 rows x 34 columns]

In [ ]:
label = df['AxPTS_category']
label.unique()

['1-2', '2-3', '0-1']
Categories (3, object): ['0-1' < '1-2' < '2-3']

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)

In [ ]:
label.values
label.values.reshape(-1, 1)
ohe.fit(label.values.reshape(-1,1))

OneHotEncoder(sparse=False)

In [ ]:
ohe.transform(label.values.reshape(-1,1))

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
label_test = np.array([['0-1'], ['1-2'], ['2-3']])

In [ ]:
ohe.transform(label_test)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
label_ohe = ohe.transform(label.values.reshape(-1, 1))

ohe_df = pd.DataFrame(label_ohe, columns=['A0-1', 'A1-2', 'A2-3'])
ohe_df

A0-1  A1-2  A2-3
0       0.0   1.0   0.0
1       0.0   0.0   1.0
2       0.0   1.0   0.0
3       0.0   1.0   0.0
4       0.0   1.0   0.0
...     ...   ...   ...
12543   1.0   0.0   0.0
12544   0.0   1.0   0.0
12545   0.0   1.0   0.0
12546   0.0   1.0   0.0
12547   0.0   0.0   1.0

[12548 rows x 3 columns]

In [ ]:
df = pd.concat([df, ohe_df], axis=1).drop('AxPTS_category', axis=1)
df

HomeTeam           AwayTeam  HomeSquad  AwaySquad  \
0                    Elche         Celta Vigo       29.0       28.0   
1          Atletico Madrid            Sevilla       32.0       34.0   
2               Villarreal        Real Madrid       37.0       41.0   
3            Athletic Club              Eibar       27.0       25.0   
4                Barcelona            Granada       31.0       39.0   
...                    ...                ...        ...        ...   
12543         Union Berlin  Arminia Bielefeld       40.0       34.0   
12544     Bayer Leverkusen           Mainz 05       35.0       34.0   
12545           Hoffenheim          Wolfsburg       40.0       37.0   
12546  Eintracht Frankfurt         FC Cologne       36.0       31.0   
12547      Greuther Fuerth      Bayern Munich       34.0       38.0   

       HomeAvgAge  AwayAvgAge  FTHG  FTAG  FTR  HTHG  ...    AxA   HPPDA  \
0            25.0        24.0   1.0   2.0    1   0.4  ...  0.974  12.440   
1            25.0        25.0   1.4   1.8    0   1.0  ...  1.082  11.820   
2            24.0        24.0   1.4   3.6    1   0.2  ...  1.502  13.016   
3            26.0        28.0   0.8   1.0    2   0.4  ...  0.552   7.822   
4            25.0        25.0   2.2   0.8    0   0.6  ...  0.330   6.064   
...           ...         ...   ...   ...  ...   ...  ...    ...     ...   
12543        26.0        24.0   1.4   0.6    0   0.8  ...  0.634  16.288   
12544        24.0        24.0   3.0   1.2    0   1.8  ...  0.830  12.608   
12545        24.0        25.0   1.6   1.4    0   0.6  ...  0.816  11.720   
12546        25.0        25.0   1.0   1.8    2   0.6  ...  1.398   7.686   
12547        24.0        24.0   0.6   4.0    1   0.0  ...  3.230  12.116   

        APPDA  month  H0-1  H1-2  H2-3  A0-1  A1-2  A2-3  
0       6.458      9   1.0   0.0   0.0   0.0   1.0   0.0  
1       8.262      9   0.0   1.0   0.0   0.0   0.0   1.0  
2       8.634      9   0.0   1.0   0.0   0.0   1.0   0.0  
3       9.050      9   0.0   1.0   0.0   0.0   1.0   0.0  
4       8.726      9   0.0   0.0   1.0   0.0   1.0   0.0  
...       ...    ...   ...   ...   ...   ...   ...   ...  
12543  13.936      9   0.0   1.0   0.0   1.0   0.0   0.0  
12544  11.290      9   0.0   1.0   0.0   0.0   1.0   0.0  
12545   8.246      9   0.0   1.0   0.0   0.0   1.0   0.0  
12546   7.152      9   0.0   1.0   0.0   0.0   1.0   0.0  
12547   9.254      9   1.0   0.0   0.0   0.0   0.0   1.0  

[12548 rows x 36 columns]

In [ ]:
df[df.isna( ).any(axis=1)]

Empty DataFrame
Columns: [HomeTeam, AwayTeam, HomeSquad, AwaySquad, HomeAvgAge, AwayAvgAge, FTHG, FTAG, FTR, HTHG, HTAG, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR, HxG, AxG, HxA, AxA, HPPDA, APPDA, month, H0-1, H1-2, H2-3, A0-1, A1-2, A2-3]
Index: []

[0 rows x 36 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12548 entries, 0 to 12547
Data columns (total 36 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   HomeTeam    12548 non-null  object 
 1   AwayTeam    12548 non-null  object 
 2   HomeSquad   12548 non-null  float64
 3   AwaySquad   12548 non-null  float64
 4   HomeAvgAge  12548 non-null  float64
 5   AwayAvgAge  12548 non-null  float64
 6   FTHG        12548 non-null  float64
 7   FTAG        12548 non-null  float64
 8   FTR         12548 non-null  int64  
 9   HTHG        12548 non-null  float64
 10  HTAG        12548 non-null  float64
 11  HS          12548 non-null  float64
 12  AS          12548 non-null  float64
 13  HST         12548 non-null  float64
 14  AST         12548 non-null  float64
 15  HF          12548 non-null  float64
 16  AF          12548 non-null  float64
 17  HC          12548 non-null  float64
 18  AC          12548 non-null  float64
 19  HY          12548 non-nul

## 모델링

In [ ]:
df_target = df['FTR'].to_numpy()
df_home = df['HomeTeam']
df_away = df['AwayTeam']

In [ ]:
df_input = df.drop(['FTR', 'HomeTeam', 'AwayTeam'], axis=1)

In [ ]:
df_target

array([1, 0, 1, ..., 0, 2, 1])

In [ ]:
df_input.to_numpy()

array([[29., 28., 25., ...,  0.,  1.,  0.],
       [32., 34., 25., ...,  0.,  0.,  1.],
       [37., 41., 24., ...,  0.,  1.,  0.],
       ...,
       [40., 37., 24., ...,  0.,  1.,  0.],
       [36., 31., 25., ...,  0.,  1.,  0.],
       [34., 38., 24., ...,  0.,  0.,  1.]])

In [ ]:
df_input[:5]

HomeSquad  AwaySquad  HomeAvgAge  AwayAvgAge  FTHG  FTAG  HTHG  HTAG    HS  \
0       29.0       28.0        25.0        24.0   1.0   2.0   0.4   0.8  11.0   
1       32.0       34.0        25.0        25.0   1.4   1.8   1.0   1.0  14.0   
2       37.0       41.0        24.0        24.0   1.4   3.6   0.2   2.0  13.8   
3       27.0       25.0        26.0        28.0   0.8   1.0   0.4   1.0   9.2   
4       31.0       39.0        25.0        25.0   2.2   0.8   0.6   0.2  14.8   

     AS  ...    AxA   HPPDA  APPDA  month  H0-1  H1-2  H2-3  A0-1  A1-2  A2-3  
0  11.6  ...  0.974  12.440  6.458      9   1.0   0.0   0.0   0.0   1.0   0.0  
1  13.8  ...  1.082  11.820  8.262      9   0.0   1.0   0.0   0.0   0.0   1.0  
2  19.2  ...  1.502  13.016  8.634      9   0.0   1.0   0.0   0.0   1.0   0.0  
3   9.8  ...  0.552   7.822  9.050      9   0.0   1.0   0.0   0.0   1.0   0.0  
4   7.0  ...  0.330   6.064  8.726      9   0.0   0.0   1.0   0.0   1.0   0.0  

[5 rows x 33 columns]

In [ ]:
from sklearn.model_selection import train_test_split # 훈련 세트, 테스트 세트 나누기 

train_input, test_input, train_target, test_target = train_test_split(df_input, df_target, test_size = 0.25, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()
ss.fit(train_input)

train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [ ]:
train_scaled.shape

(9411, 33)

In [ ]:
train_target.shape

(9411,)

In [ ]:
test_scaled.shape

(3137, 33)

In [ ]:
test_target.shape

(3137,)

In [ ]:
#모델 훈련 후 정확도 측정
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=3) # 참고하는 이웃의 수를 3으로 지정
kn.fit(train_scaled, train_target)
print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.677398788651578
0.43066624163213263


In [ ]:
print(kn.classes_)

[0 1 2]


In [ ]:
#모델 예측값 알아보기
print(kn.predict(test_scaled[:5]))

[0 0 1 0 0]


In [ ]:
import numpy as np
proba = kn.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=4))


[[0.6667 0.3333 0.    ]
 [1.     0.     0.    ]
 [0.3333 0.6667 0.    ]
 [1.     0.     0.    ]
 [0.6667 0.3333 0.    ]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn49 = KNeighborsClassifier(n_neighbors=49) # 참고하는 이웃의 수를 49로 지정
kn49.fit(train_scaled, train_target)
print(kn49.score(train_scaled, train_target))
print(kn49.score(test_scaled, test_target))

0.5176920624800765
0.47975773031558816


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn100 = KNeighborsClassifier(n_neighbors=100) # 참고하는 이웃의 수를 100으로 지정
kn100.fit(train_scaled, train_target)
print(kn100.score(train_scaled, train_target))
print(kn100.score(test_scaled, test_target))

0.5121666135373499
0.47816385081287854


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn150 = KNeighborsClassifier(n_neighbors=150) # 참고하는 이웃의 수를 150으로 지정
kn150.fit(train_scaled, train_target)
print(kn150.score(train_scaled, train_target))
print(kn150.score(test_scaled, test_target))

0.5094038890659867
0.4839018170226331


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn170 = KNeighborsClassifier(n_neighbors=170) # 참고하는 이웃의 수를 170으로 지정
kn170.fit(train_scaled, train_target)
print(kn170.score(train_scaled, train_target))
print(kn170.score(test_scaled, test_target))

0.5104664754011263
0.484220592923175


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn152 = KNeighborsClassifier(n_neighbors=152) # 참고하는 이웃의 수를 170으로 지정
kn152.fit(train_scaled, train_target)
print(kn152.score(train_scaled, train_target))
print(kn152.score(test_scaled, test_target))

0.5098289236000425
0.48804590372967804


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn151 = KNeighborsClassifier(n_neighbors=151) # 참고하는 이웃의 수를 170으로 지정
kn151.fit(train_scaled, train_target)
print(kn151.score(train_scaled, train_target))
print(kn151.score(test_scaled, test_target))

0.5097226649665285
0.4851769206248008


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn149 = KNeighborsClassifier(n_neighbors=149) # 참고하는 이웃의 수를 170으로 지정
kn149.fit(train_scaled, train_target)
print(kn149.score(train_scaled, train_target))
print(kn149.score(test_scaled, test_target))

0.5105727340346403
0.4861332483264265


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn155 = KNeighborsClassifier(n_neighbors=155) # 참고하는 이웃의 수를 170으로 지정
kn155.fit(train_scaled, train_target)
print(kn155.score(train_scaled, train_target))
print(kn155.score(test_scaled, test_target))

0.5103602167676123
0.4851769206248008


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn155 = KNeighborsClassifier(n_neighbors=155) # 참고하는 이웃의 수를 170으로 지정
kn155.fit(train_scaled, train_target)
print(kn155.score(train_scaled, train_target))
print(kn155.score(test_scaled, test_target))

0.5103602167676123
0.4851769206248008


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn156 = KNeighborsClassifier(n_neighbors=156) # 참고하는 이웃의 수를 170으로 지정
kn156.fit(train_scaled, train_target)
print(kn156.score(train_scaled, train_target))
print(kn156.score(test_scaled, test_target))

0.5098289236000425
0.48485814472425887


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn154 = KNeighborsClassifier(n_neighbors=154) # 참고하는 이웃의 수를 170으로 지정
kn154.fit(train_scaled, train_target)
print(kn154.score(train_scaled, train_target))
print(kn154.score(test_scaled, test_target))

0.5096164063330145
0.484220592923175


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn157 = KNeighborsClassifier(n_neighbors=157) # 참고하는 이웃의 수를 170으로 지정
kn157.fit(train_scaled, train_target)
print(kn157.score(train_scaled, train_target))
print(kn157.score(test_scaled, test_target))

0.5102539581340984
0.48485814472425887


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn160 = KNeighborsClassifier(n_neighbors=160) # 참고하는 이웃의 수를 170으로 지정
kn160.fit(train_scaled, train_target)
print(kn160.score(train_scaled, train_target))
print(kn160.score(test_scaled, test_target))

0.5100414408670705
0.4839018170226331


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn152 = KNeighborsClassifier(n_neighbors=155) 
kn152.fit(train_scaled, train_target)
print(kn152.score(train_scaled, train_target))
print(kn152.score(test_scaled, test_target))

0.5103602167676123
0.4851769206248008


In [ ]:
print(kn152.predict_proba(test_scaled[:5]))

[[0.42580645 0.27096774 0.30322581]
 [0.47741935 0.28387097 0.23870968]
 [0.39354839 0.34193548 0.26451613]
 [0.7483871  0.12903226 0.12258065]
 [0.44516129 0.29677419 0.25806452]]


In [ ]:
#모델 예측값 알아보기
print(kn152.predict(test_scaled[:5]))

# 실제는 AHADH
#      10120

[0 0 0 0 0]


In [ ]:
y_pred = kn152.predict(test_scaled)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score, f1_score

accuracy = accuracy_score(test_target, y_pred)
print('Accuracy :', accuracy)

Accuracy : 0.4851769206248008


In [ ]:
f1 = f1_score(test_target, y_pred, average='weighted')
print("F1 Score:", f1)

F1 Score: 0.4028876050487566
